# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_city_uuid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='city',
            table='villes',
        ),
    ]
