# Generated by Django 6.0.2 on 2026-03-24 01:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='receipt_url',
        ),
        migrations.AddField(
            model_name='deposit',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='deposits/receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp'])]),
        ),
    ]
