# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0002_remove_deposit_receipt_url_deposit_receipt_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deposit',
            table='versements',
        ),
    ]
