# Generated by Django 6.0.2 on 2026-03-23 18:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True)),
                ('delivered_qty_gasoline', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivered_qty_diesel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_date', models.DateField()),
                ('truck_number', models.CharField(blank=True, max_length=50, null=True)),
                ('driver_name', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.ordersupplier')),
            ],
            options={
                'db_table': 'deliveries',
            },
        ),
    ]
