# Generated by Django 6.0.2 on 2026-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_note',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='notes',
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivery_notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
