# Generated by Django 6.0.3 on 2026-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_delivery_delivery_note_remove_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
