# Generated by Django 6.0.3 on 2026-03-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_delivery_driver_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='missing_qty_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery',
            name='missing_qty_gasoline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
