# Generated by Django 6.0.3 on 2026-03-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_delivery_missing_qty_diesel_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='delivery',
            table='reception',
        ),
    ]
