# Generated by Django 6.0.2 on 2026-02-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Administrateur'), ('admin', "Propriétaire d'une station-service"), ('manager', "Gérant d'une station-service")], default='super_admin', max_length=20),
        ),
    ]
