# Generated by Django 6.0.3 on 2026-03-25 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_user_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, help_text='Identifiant unique (affichage / référence).', max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, error_messages={'invalid': 'Veuillez entrer un mail valide'}, max_length=254, null=True, unique=True),
        ),
    ]
