# Generated by Django 6.0.2 on 2026-02-14 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
