# Generated by Django 6.0.3 on 2026-03-25 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text="Date à partir de laquelle ces prix s'appliquent.", unique=True, verbose_name="Date d'application")),
                ('price_gasoline', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix essence (par litre)')),
                ('price_diesel', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix gazoil (par litre)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grille de prix',
                'verbose_name_plural': 'Grilles de prix',
                'db_table': 'product_price',
                'ordering': ['-effective_from'],
            },
        ),
    ]
