# Generated by Django 6.0.3 on 2026-03-25 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_price', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productprice',
            name='uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
