# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dailystock',
            table='stock',
        ),
    ]
