# Generated by Django 6.0.2 on 2026-05-17 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_stock', '0002_alter_dailystock_table'),
        ('tank', '0002_alter_tank_options_tank_created_at_tank_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailystock',
            name='previous_stock_diesel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='dailystock',
            name='previous_stock_gasoline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DailyStockTankLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('recorded_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_lines', to='daily_stock.dailystock')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tank.tank')),
            ],
            options={
                'db_table': 'stock_cuve_ligne',
                'constraints': [models.UniqueConstraint(fields=('daily_stock', 'tank'), name='unique_daily_stock_tank_line')],
            },
        ),
    ]
