# Generated by Django 6.0.2 on 2026-06-14 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refund', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='refund',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
