# Generated by Django 6.0.2 on 2026-03-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_employee_uuid_employee_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='owner',
        ),
    ]
