# Generated by Django 6.0.3 on 2026-03-26 15:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_owner'),
        ('stations', '0002_station_stock_diesel_station_stock_gasoline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='station',
        ),
        migrations.CreateModel(
            name='EmployeeStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_station_uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_manager', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'db_table': 'employee_stations',
            },
        ),
    ]
