# Generated by Django 6.0.3 on 2026-03-26 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_remove_employee_station_employeestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
