# Generated by Django 6.0.3 on 2026-03-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_employee_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='personnel',
        ),
    ]
