# Generated by Django 6.0.3 on 2026-03-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeestation',
            table='personnel_station',
        ),
    ]
