# Generated by Django 6.0.2 on 2026-06-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0001_initial'),
        ('inventory', '0006_inventory_previous_stock_diesel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credits', to='inventory.inventory'),
        ),
    ]
