# Generated by Django 6.0.3 on 2026-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='stock_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='station',
            name='stock_gasoline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
