# Generated by Django 6.0.2 on 2026-02-14 15:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_latitude_station_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='station_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
