# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0002_station_stock_diesel_station_stock_gasoline'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
        migrations.AlterModelTable(
            name='stationmanager',
            table='station_gerant',
        ),
    ]
