# Generated by Django 6.0.3 on 2026-03-25 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='delivery',
        ),
    ]
