# Generated by Django 6.0.3 on 2026-03-29 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_inventory_delivery'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='inventory',
            table='stock_reel',
        ),
    ]
