# Generated by Django 6.0.2 on 2026-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_created_at'),
        ('wallet', '0004_accounthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='previous_stock_diesel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='previous_stock_gasoline',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='reading_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='source',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='InventoryWalletAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.account')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_allocations', to='inventory.inventory')),
            ],
            options={
                'db_table': 'stock_reel_wallet',
                'constraints': [models.UniqueConstraint(fields=('inventory', 'account'), name='unique_inventory_wallet_allocation')],
            },
        ),
    ]
