# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_name_alter_account_station_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='account',
            table='comptes',
        ),
    ]
