# Generated by Django 6.0.3 on 2026-03-28 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_supplier_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='price_diesel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Prix gazoil'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='price_gasoline',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Prix essence'),
        ),
    ]
