# Generated by Django 6.0.3 on 2026-03-29 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_position_uuid'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='position',
            table='postes',
        ),
    ]
