# Generated by Django 6.0.2 on 2026-03-23 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pumps', '0002_pump_pump_uuid_pumpreading_pump_reading_uuid'),
        ('stations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('qty_gasoline', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('qty_diesel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price_gasoline', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price_diesel', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pump_reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pumps.pumpreading')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
            options={
                'db_table': 'sales',
            },
        ),
    ]
