# Generated by Django 6.0.2 on 2026-02-14 17:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0004_stationmanager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('essence', 'Essence'), ('gazole', 'Gazole')], max_length=255)),
                ('initial_index', models.IntegerField()),
                ('current_index', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station')),
            ],
        ),
        migrations.CreateModel(
            name='PumpReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_index', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_index', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity_sold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reading_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='pumps.pump')),
            ],
        ),
    ]
