# Generated by Django 6.0.2 on 2026-03-23 20:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='pump_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='pump_reading_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
