# Generated by Django 6.0.2 on 2026-03-23 21:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0002_pump_pump_uuid_pumpreading_pump_reading_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_reset_uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('previous_initial_index', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('previous_current_index', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reset_initial_index', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reset_current_index', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resets', to='pumps.pump')),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pump_resets',
            },
        ),
    ]
