# Generated by Django 6.0.2 on 2026-03-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0003_pumpreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pumpreading',
            name='initial_index',
        ),
    ]
