# Generated by Django 6.0.3 on 2026-03-29 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0004_remove_pumpreading_initial_index'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pump',
            table='pompe_station',
        ),
        migrations.AlterModelTable(
            name='pumpreading',
            table='pumpe_index',
        ),
    ]
