# Generated by Django 6.0.2 on 2026-05-17 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventory_previous_stock_diesel_and_more'),
        ('pumps', '0005_alter_pump_table_alter_pumpreading_table'),
        ('stations', '0003_alter_station_table_alter_stationmanager_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpReadingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_batch', to='inventory.inventory')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_reading_batches', to='stations.station')),
            ],
            options={
                'db_table': 'pompe_lecture_lot',
            },
        ),
        migrations.AddField(
            model_name='pumpreading',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='pumps.pumpreadingbatch'),
        ),
        migrations.AddConstraint(
            model_name='pumpreadingbatch',
            constraint=models.UniqueConstraint(fields=('station', 'reading_date'), name='unique_pump_reading_batch_station_date'),
        ),
    ]
