# Generated by Django 6.0.2 on 2026-05-20 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pumps', '0006_pumpreadingbatch_pumpreading_batch_and_more'),
        ('tank', '0003_tank_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pump',
            name='tank',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tank.tank'),
            preserve_default=False,
        ),
    ]
