# Generated by Django 6.0.2 on 2026-05-16 17:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tank_uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('actual_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('product', models.CharField(choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel')], default='gasoline', max_length=100)),
            ],
        ),
    ]
