# Generated by Django 6.0.2 on 2026-05-16 17:12

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_alter_station_table_alter_stationmanager_table'),
        ('tank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='tank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='stations.station'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tank',
            name='product',
            field=models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Gazoil')], default='gasoline', max_length=100),
        ),
        migrations.AlterField(
            model_name='tank',
            name='tank_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterModelTable(
            name='tank',
            table='cuve_station',
        ),
    ]
