# Generated by Django 6.0.2 on 2026-05-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tank', '0002_alter_tank_options_tank_created_at_tank_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='max_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
