# Generated by Django 6.0.3 on 2026-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_order_uuid_ordersupplier_order_supplier_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requested_qty_diesel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='requested_qty_gasoline',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
