# Generated by Django 6.0.3 on 2026-03-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_requested_qty_diesel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
