# Generated by Django 6.0.3 on 2026-03-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_order_driver_name_order_truck_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_order_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/purchase_orders/'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_order_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
