# Generated by Django 6.0.3 on 2026-03-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_driver_phone_order_purchase_order_file_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='commande',
        ),
        migrations.AlterModelTable(
            name='ordersupplier',
            table='commande_fournisseur',
        ),
    ]
