# Generated by Django 6.0.2 on 2026-05-16 18:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_table_alter_ordersupplier_table'),
        ('tank', '0002_alter_tank_options_tank_created_at_tank_station_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_tank_uuid', models.UUIDField(blank=True, default=uuid.uuid4, null=True)),
                ('product', models.CharField(choices=[('gasoline', 'Essence'), ('diesel', 'Gazoil')], default='gasoline', max_length=100)),
                ('product_qty', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tanks', to='order.order')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_tanks', to='tank.tank')),
            ],
            options={
                'db_table': 'commande_cuve',
            },
        ),
    ]
