# Generated by Django 6.0.2 on 2026-05-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_ordertank'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersupplier',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordersupplier',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ordersupplier',
            name='truck_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
